### ISSUE TITLE
Punchlist

### ISSUE THREAD

**Issue by hunterboerner** [stereowrench/visual_garden#33]
- [ ] Timezone picker should be more user friendly
- [x] Add "add to garden" on LibrarySeed#Show
- [x] Clicking back on seeds from show LibrarySeeds should keep filter
- [x] ~~can't read my handwriting~~
- [x] ~~can't read my handwriting~~
- [ ] Remove "remaining days" from year-round items
- [x] Copy-edit "nurse your plants"
- [x] "new bed" on planner is not obvious
- [x] New bed should not leave planner page
- [ ] Recommended plantables for free spaces
- [x] Add species link to library seeds
- [x] Explain what "refuse date" is
- [ ] Link homepage on planner tip
- [ ] Home should have notification badge
- [x] Copy-edit on Product#new
- [x] Name on Product#new should not autocomplete
- [x] Home transfer should not take you away from the home page
- [ ] More color?
- [x] planner upcoming should still allow clicking on items in the garden inventory

**Comment by chris-marrero** [comment]
- [ ] Plantables missing fields.
- [ ] Link on seeds page in gardens to library
- [ ] Add copy
